title: PegaseUIData
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

source: docs

aux_links:
  GitHub: https://github.com/thierryH91200/PegaseUIData

nav_sort: case_sensitive
