title: PegaseUIData
description: Gestion financière personnelle gratuite pour macOS
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Dossier source
source: docs

# Navigation
navigation:
  - title: Français
    url: /index.fr.md
  - title: English
    url: /index.en.md
