title: PegaseUIData
description: Gestion financière personnelle gratuite pour macOS
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation links
# Note: These links will appear as top navigation if supported by the theme.
navigation:
  - title: Français
    url: index.fr.md
  - title: English
    url: index.en.md
